### ISSUE TITLE
Python scripts working on brick, not on the apache web

### ISSUE THREAD

**Issue by gdbiomax** [okanulas/Pathfind3r#1]
I have issue of trying to run the web interface socket_server.py from web php, 
![pm](https://cloud.githubusercontent.com/assets/22153480/18525682/be4431d0-7a7a-11e6-87b5-c8181eecd490.jpg).
tried  sudo python /home/robot/myproject/socket_server.py   it works
but not on web php, checked the code on PHP
    putenv('PYTHONPATH=/var/www/.local/lib/python2.7/site-packages:/var/www/.local/lib/python2.7/site-packages:');
        $start_server = shell_exec('sudo python /var/www/pathfinder/python/socket_server.py' );
anything need to setup?

**Comment by okanulas** [comment]
Hi,
Unfortunatelly i'm on holiday and i dont have my computer with me, i have my phone only. I can examine the problem when i get back. But it seems like php doesnt have permission to access to run python scripts. Setting chmod 777 for the scripts folder could solve the problem.

**Comment by gdbiomax** [comment]
Thanks for replying.
I tried ‘chmod -R 777 /home/robot/myproject’， since the .py I put in this folder.
changed your code to       shell_exec('sudo python /home/robot/myproject/socket_server.py' );
![t](https://cloud.githubusercontent.com/assets/22153480/18595793/81246038-7c03-11e6-9409-ea7d7f383ac6.jpg)
The socket_server error dispeared, but It still doesn't run the .py.  
when I ran ' sudo python /home/robot/myproject/socket_server.py' , I have to enter the password 'maker' to make it run. 
I think this may cause php still not run .py.

**Comment by gdbiomax** [comment]
I also tried 'sudo visudo', here is my screen shot
![t2](https://cloud.githubusercontent.com/assets/22153480/18596897/ac35d324-7c08-11e6-9cbe-02eb3cef141a.jpg)
after that, it still not working.

**Comment by okanulas** [comment]
Below is my sudoers file. Using these values could help. Update using sudo nano /etc/sudoers command. Your screenshot displays sudoers.tmp. it should be just sudoers, with no extension.  Please let me know if it works.

#

# This file MUST be edited with the 'visudo' command as root.

#

# Please consider adding local content in /etc/sudoers.d/ instead of

# directly modifying this file.

#

# See the man page for details on how to write a sudoers file.

#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:$

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification

root    ALL=(ALL:ALL) ALL
robot   ALL=(ALL:ALL) NOPASSWD:ALL
www-data ALL=(ALL) NOPASSWD: ALL

# Allow members of group sudo to execute any command

%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

**Comment by gdbiomax** [comment]
![sudoer](https://cloud.githubusercontent.com/assets/22153480/18620295/8fd49a74-7dcc-11e6-82a8-47d17f25f7e8.jpg)
I followed your instruction and used 'sudo nano /etc/sudoers ' to modify the file. 
using Filezilla like this 
![mp](https://cloud.githubusercontent.com/assets/22153480/18620341/cf89c422-7dcd-11e6-91e7-507d0870fb7d.jpg)
go to localhost,nothing happed
![mp](https://cloud.githubusercontent.com/assets/22153480/18620356/169cc120-7dce-11e6-96f2-96e2215eaa63.jpg)

have no clue now.

**Comment by gdbiomax** [comment]
Should apache be installed on EV3 or remote computer?

**Comment by okanulas** [comment]
It should be installed on Ev3. I've prepared a test page. 
1. Save the below code as "test.php"
2. Upload to the root folder of the project.
3. Run with the browser
4. Please send the output to me?

i think problem is about the paths. I used some hardcoded paths for the project.

```
<?php
echo "\n-----------------------------\n";
echo shell_exec("whoami");
echo "\n-----------------------------\n";
echo shell_exec("php -v  2>&1");
echo "\n-----------------------------\n";
echo shell_exec("ls -lah 2>&1");
echo "\n-----------------------------\n";
echo shell_exec("pwd 2>&1");
echo "\n-----------------------------\n";
echo shell_exec('sudo python python/socket_server.py 2>&1' );
echo "\n-----------------------------\n";
?>
```

**Comment by gdbiomax** [comment]
I have this return:

----------------------------- www-data ----------------------------- PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 14:48:25) Copyright (c) 1997-2016 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies ----------------------------- total 28K drwxrwxrwx 2 root root 4.0K Sep 20 03:44 . drwxrwxrwx 4 root root 4.0K Sep 20 03:44 .. -rwxrwxrwx 1 root root 11K Sep 16 20:23 index.html -rw-r--r-- 1 robot robot 20 Sep 20 03:32 info.php -rw-rw-rw- 1 robot robot 445 Sep 20 03:41 test.php ----------------------------- /var/www/html ----------------------------- python: can't open file 'python/socket_server.py': [Errno 2] No such file or directory -----------------------------

**Comment by gdbiomax** [comment]
![pm](https://cloud.githubusercontent.com/assets/22153480/18657362/c69bb836-7eb6-11e6-8076-4ac5a1ab5f37.jpg)

I can browse the py file in the subfolder

**Comment by okanulas** [comment]
It seems like the test.php is at the /var/www/html folder could you put it into the Pathfinder folder and send the output?

**Comment by gdbiomax** [comment]
![pm](https://cloud.githubusercontent.com/assets/22153480/18677385/cedd6288-7f15-11e6-8d05-b1c4a0cc1e4f.jpg)

**Comment by gdbiomax** [comment]
So far, I made some fuctions on the web work except socket_server, draw svg and maze, display status.
I am not sure if the socket_server is runing, but I didn't hear the reminder" Socket_server is running"
looks like it is running, otherwise those php should be excuted.
now, why some functions are still working properly.

**Comment by gdbiomax** [comment]
![pm](https://cloud.githubusercontent.com/assets/22153480/18685208/4bf08048-7f34-11e6-9f3d-d0c1750cddd2.jpg)
![pm](https://cloud.githubusercontent.com/assets/22153480/18685280/975f1ed6-7f34-11e6-8d3e-41206841344c.jpg)

**Comment by okanulas** [comment]
I figured out the problem. I was using absolute paths for the project. I changed them to relative paths and updated the project. Everything should be ok now. You can download from git. I've also added a stop server button to the web interface. Start server and stop server buttons call python scripts and execution time is very slow. You should hear "Server is started" from the brick but it can take up 2 minutes. Stop server button shuts down all the python processes.. You should wait for 1-2 minutes to take effect.

**Comment by gdbiomax** [comment]
Thanks Okanulas, it is working on mine.
